/**
 * Archive. The lint no longer imports this list (SPEC.md retired
 * R-NO-SACRED-NAMES). Kept so `advisory/prohibited-names.txt` still has a
 * matching in-repo copy. Do not wire this back into `lintPack`.
 */
export const PROHIBITED_NAMES: readonly string[] = [
  'Shakyamuni',
  'Buddha',
  'Amitabha',
  'Amida',
  'Amitayus',
  'Avalokiteshvara',
  'Avalokiteśvara',
  'Guanyin',
  'Kannon',
  'Chenrezig',
  'Manjushri',
  'Mañjuśrī',
  'Wenshu',
  'Monju',
  'Samantabhadra',
  'Puxian',
  'Fugen',
  'Ksitigarbha',
  'Kṣitigarbha',
  'Dizang',
  'Jizo',
  'Mahasthamaprapta',
  'Mahāsthāmaprāpta',
  'Dashizhi',
  'Daesaeji',
  'Seishi',
  'Tara',
  'Tārā',
  'Drolma',
  'Maitreya',
  'Mila',
  'Milarepa',
  'Padmasambhava',
  'Tsongkhapa',
  'Nagarjuna',
  'Nāgārjuna',
  'Atisha',
  'Shantideva',
  'Śāntideva',
  'Bodhidharma',
];
